# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 14:06
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=240, unique=True)),
                ('carga_horaria', models.SmallIntegerField(db_column='CARGA_HORARIA')),
                ('teoria', models.DecimalField(blank=True, db_column='TEORIA', decimal_places=0, max_digits=3, null=True)),
                ('pratica', models.DecimalField(blank=True, db_column='PRATICA', decimal_places=0, max_digits=3, null=True)),
                ('competencias', models.TextField(blank=True, db_column='COMPETENCIAS', null=True)),
                ('habilidades', models.TextField(blank=True, db_column='HABILIDADES', null=True)),
                ('conteudo', models.TextField(blank=True, db_column='CONTEUDO', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(db_column='ANO')),
                ('semestre', models.CharField(db_column='SEMESTRE', max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ofertado', models.ForeignKey(blank=True, db_column='ano_ofertado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DisciplinaOfertada')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=1)),
                ('turno', models.CharField(blank=True, max_length=15, null=True)),
                ('disciplina_ofertada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.DisciplinaOfertada')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(default='C', max_length=1, verbose_name='Tipo de usuário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('sala', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(blank=True, db_column='id_turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nome_disciplina',
            field=models.ForeignKey(blank=True, db_column='nome_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre_ofertado',
            field=models.ForeignKey(blank=True, db_column='semestre_ofertado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='ano_ofertado',
            field=models.ForeignKey(blank=True, db_column='ano_ofertado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma',
            field=models.ForeignKey(blank=True, db_column='id_turma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='nome_disciplina',
            field=models.ForeignKey(blank=True, db_column='nome_disciplina', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='semestre_ofertado',
            field=models.ForeignKey(blank=True, db_column='semestre_ofertado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='sigla_curso',
            field=models.ForeignKey(blank=True, db_column='sigla_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together=set([('disciplina_ofertada', 'identificador')]),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_aluno',
            field=models.ForeignKey(blank=True, db_column='ra_aluno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together=set([('ano', 'semestre', 'disciplina')]),
        ),
        migrations.AlterUniqueTogether(
            name='cursoturma',
            unique_together=set([('sigla_curso', 'nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma')]),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ManyToManyField(through='core.Matricula', to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('ra_aluno', 'nome_disciplina', 'ano_ofertado', 'semestre_ofertado', 'id_turma')]),
        ),
    ]
